Post http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees
Content-Type: application/json

{
  "name": "Wayne Silva",
  "email": "wayne33@cv.com"
}

###

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33

###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/8d79a8ae-fa1c-4fea-aec2-c8e9cbe8cd16/attendees?query=Mário